---
name: ci

on:
  push:
    branchs: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Tests
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      
      - name: MegaLinter
        uses: oxsecurity/megalinter@v6.15.0
